---
- name: Install mysql
  hosts: dbserver
  become: True
  tasks:
    - name: Install update
      ansible.builtin.apt:
        update_cache: yes
    - name: Install mysql
      apt:
        name: mysql-server
    - name: Change bind-adress in mysql config
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^\s*bind-address\s+'
        line: 'bind-address = 0.0.0.0'
        backrefs: yes
    - name: Restart Apache server
      command: systemctl restart mysql.service
  

- name: Clone a Git repository
  hosts: dbserver
  become: True
  tasks:
    - name: Clone git repository
      ansible.builtin.git:
        repo: "https://github.com/siamon123/warehouse-inventory-system.git"
        dest: "/var/www/warehouse-inventory-system/"
        force: yes